### ISSUE TITLE
Multiple agents on the same machine not able to distribute available free space 

### ISSUE THREAD

**Issue by hchemanchula** [ashwanthkumar/go-gocd#7]
Hi,

I have setup two go-agents (18.2v) on the same machine, but the free space available on the machine is not shared between them, go-agent has (1000 GB) and the go-agent-1 has (290 MB). Any help in fixing this is appreciated.

Thanks,
Hemanth

**Comment by ashwanthkumar** [comment]
@hchemanchula Can you please direct this question to [go-cd@googlegroups.com](mailto:go-cd@googlegroups.com) ? This is not related to this project.
